[versions]
springDependencyManagementVersion = "1.1.7"
jigVerasion = "2025.10.1"
springBootVersion = "3.5.8"
springCloudVersion = "2025.0.0"
springCloudAwsVersion = "3.4.1"
logbackAccessSpringVersion = "4.7.0"
logbackAccessTomcatVersion = "2.0.7"
lombokVersion = "1.18.42"
thymeleafExtrasSpringsecurity6Version = "3.1.3.RELEASE"
apacheHttpcomponentsClient5Version = "5.5.1"
thymeleafLayoutDialectVersion = "3.3.0"
mybatisSpringbootStarterVersion = "3.0.5"

[plugins]
spring-boot-plugin = { id = "org.springframework.boot", version.ref = "springBootVersion" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion"}
jig-plugin = { id = "org.dddjava.jig-gradle-plugin", version.ref = "jigVerasion" }

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBootVersion" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloudVersion" }
spring-cloud-aws-dependencies = { module = "io.awspring.cloud:spring-cloud-aws-dependencies", version.ref = "springCloudAwsVersion" }
logback-access-spring = { module = "dev.akkinoc.spring.boot:logback-access-spring-boot-starter", version.ref = "logbackAccessSpringVersion" }
logback-access-tomcat = { module = "ch.qos.logback.access:logback-access-tomcat", version.ref = "logbackAccessTomcatVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
mybatis-spring-boot-starter = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "mybatisSpringbootStarterVersion" }
mybatis-spring-boot-starter-test = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter-test", version.ref = "mybatisSpringbootStarterVersion" }

# Spring Boot Starters
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

# Spring Cloud Starters
spring-cloud-starter-config = { module = "org.springframework.cloud:spring-cloud-starter-config" }
spring-cloud-starter-bus-amqp = { module = "org.springframework.cloud:spring-cloud-starter-bus-amqp" }

# Spring Framwork
spring-session-data-redis = { module = "org.springframework.session:spring-session-data-redis" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

# Thymeleaf Extras
thymeleaf-extras-springsecurity6 = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6", version.ref = "thymeleafExtrasSpringsecurity6Version" }
thymeleaf-layout-dialect = { module = "nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect", version.ref = "thymeleafLayoutDialectVersion" }

# AWS Spring Cloud
awspring-cloud-starter = { module = "io.awspring.cloud:spring-cloud-aws-starter" }
awspring-cloud-starter-s3 = { module = "io.awspring.cloud:spring-cloud-aws-starter-s3" }
awspring-cloud-starter-sqs = { module = "io.awspring.cloud:spring-cloud-aws-starter-sqs" }
awspring-cloud-starter-parameter-store = { module = "io.awspring.cloud:spring-cloud-aws-starter-parameter-store" }
awspring-cloud-starter-secrets-manager = { module = "io.awspring.cloud:spring-cloud-aws-starter-secrets-manager" }
awspring-cloud-starter-metrics = { module = "io.awspring.cloud:spring-cloud-aws-starter-metrics" }
awspring-cloud-aws-testcontainers = { module = "io.awspring.cloud:spring-cloud-aws-testcontainers" }

# Micrometer & OpenTelemetry
micrometer-tracing-bridge-otel = { module = "io.micrometer:micrometer-tracing-bridge-otel" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

# Database Drivers
h2 = { module = "com.h2database:h2" }

# Apache HttpComponents
apache-httpcomponents-client5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "apacheHttpcomponentsClient5Version" }


